name: ✨ Feature Request
description: Suggest an idea to improve the TLF Packager GUI
title: "[FEATURE] "
labels: [enhancement]

body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "It’s hard to reorder outputs quickly when there are 200+ files."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: "Add drag-and-drop reordering in the GUI."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions you've considered.
      placeholder: "Keyboard shortcuts or batch sorting."
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references about the feature.
      placeholder: "Screenshots, mockups, or reference tools"
